### ISSUE TITLE
Warning after installation of original V2.0.1

### ISSUE THREAD

**Issue by NetSecond** [akeeba/engage#82] opened 2021-05-16 15:22 UTC
Hi,

after download and install version 2.0.1 I get following messages after installation:

![engage_problem_1](https://user-images.githubusercontent.com/26506313/118402631-006f9280-b66b-11eb-829d-a4ad8d819d55.jpg)

Engage is running fine then.
I tested it with different joomla installations with the original package and with joomla 3.x.x and 4.0.0 beta 8.

**Comment by nikosdion** [comment] 2021-05-17 06:28
This is not a bug in our software. It's how Joomla works. You already have a newer version of FOF installed by means of having installed an Akeeba extension released after Engage 2.0.1 e.g. Akeeba Backup, Admin Tools, LoginGuard etc. 

FOF is the common backend framework for our extensions. FEF is the common frontend (CSS and JS) framework for our extensions. We don't want an older extension to install an older version of either framework as this could reintroduce a bug we've fixed in a newer version. 

Unfortunately, Joomla does NOT have any kind of dependency management. So we have to fake it. The only way to fake it is use the pre-installation script Joomla allows for installing an extension (either of these frameworks is a Joomla extension) and return false if there's a new version, telling Joomla not to install this older version. Joomla will then _IDIOTICALLY_ print a message about the installation failing when the installation (of the extension you told it to install) HAS NOT FAILED!

So, in a few short words: Joomla's extension installation experience is crap.

The only thing I can address it is by rewriting Engage using core Joomla MVC, without using our own frameworks. I will, it's a decision I've made for all of our software but doing this for Engage is currently not a top priority. I am working on our paid extensions and the extensions we use on our site first. If we don't make a living we obviously can't spend any time working on our free of charge software :)

**Closed as completed by nikosdion** 2021-05-17 06:28 UTC
Labels: invalid

**Comment by NetSecond** [comment] 2021-05-17 12:56
I know about your hard work and please remember, that I only showed, whats happend, when I install your great package.
So, in this case, everything is fine ....

**Comment by nikosdion** [comment] 2021-05-17 16:42
It's really not a problem, but I do need to explain why this happens. It's very much non-obvious to the observer.

This, along with the fact that Joomla 4's core backend framework finally caught up with most of what I was doing ten years ago, played their part in my decision to move everything to using the core frameworks. In the end of the day I very much prefer having to maintain less code 😄
