### ISSUE TITLE
Recaptcha not showing for guests or registered

### ISSUE THREAD

**Issue by polygonrenegade** [akeeba/engage#27] opened 2020-05-12 19:25 UTC
Hi, For some reason the ReCaptcha is only showing when I log in as my super user.

I have set the options to 'Use Global (CAPTCHA - ReCAPTCHA)' and with 'All' or 'all but comment administrators'.

I've set permissions as per the setup guide.

I can see the comment section as a public visitor to the site and I can see the fields 'Name', 'Email address' and the editor window, then the 'Post your comment' button but no Captcha image.

When I login to the site and load the page it appears?

Sorry if this is my mistake in configuration but I've tried everything I can think of.

**Comment by nikosdion** [comment] 2020-05-12 19:53
I am a bit confused as to what you're trying to do. I cannot reproduce your issue.

First of all, there are two distinct options. “CAPTCHA for comments“ determines which CAPTCHA plugin will be used. If you select Use Global it will use whatever you have selected in Joomla's Global Configuration page (as it tells you, it's the ReCAPTCHA plugin).

So the first question I have is: have you configured the CAPTCHA - ReCAPTCHA plugin on your site? Have you confirmed it's working by using e.g. with Joomla's contact component?

The second option in Akeeba Engage is “Use CAPTCHA for these users“. It does exactly as advertised. If you set it to All everyone has to solve a CAPTCHA. If you set it to Guest only guest comments will need to solve a CAPTCHA. I've tested that and it works.

Here's the thing. ReCAPTCHA is a “smart“ CAPTCHA. It remember your browser for a while. If you've already solved ReCAPTCHA recently on your site it will not ask you to solve a new CAPTCHA. So my second question is: did that get you confused?

Regarding the comment section, you said that when you are NOT logged in you see the Name and Email address fields. This is correct. You are not logged in, you need to manually type in your name and email address. When you are logged in these fields do not appear because your Joomla user profile – which we already have access to since you are logged in – already has this information. It'd be silly having you retype your name and email address when it's already on file.

I am tentatively closing this with the label "invalid" because it cannot be reproduced. If you come up with instructions that would let me reproduce the issue I'll reopen this issue and change the label accordingly.

**Closed by nikosdion** 2020-05-12 19:53 UTC
Labels: invalid

**Comment by polygonrenegade** [comment] 2020-05-12 20:22
Yes - sorry. I am using and have configured Recaptcha API keys version 2 and can confirm it is working and configured ok.

Yes I've set the second setting to both 'All' and 'All but admins'

So I was expecting either of those options to show the capture for both guests and logged in registered users.

Ah - it might well be the fact that it remembers. I might have solved the captcha as my super user then logged out thinking it would reset due to logging out I'll go and try it on another machine as a guest and see if it shows up again.

(My comment about seeing the email field was just to let you know that I was correctly seeing those as a not logged in user (was just for information to say it all looked correct but no Captcha - but your explanation of it remembering that I ;d done it might well be the answer.

Thanks for your time and I'll come back to you if it isn't the remembering of the captcha. Thanks so much for developing this package. Very timely for my current scenario and always like using your components!

Sure - happy for this to be closed invalid as it is probably down to my misunderstanding of the Captcha system.

Thanks Again!

**Comment by Pablo234** [comment] 2020-07-24 19:21
It seems plugin doesnt pick de global captcha settings. 

In Joomla Global settings I got 


1. Global > re captcha
2  re captcha
3. None


You should specify  recaptcha (2nd opción) If you use Global the captcha doesnt appear for guest users. 

Justo a bug imo.

**Comment by nikosdion** [comment] 2020-07-25 12:52
Using the global setting works. What doesn't work is the "Anyone but comment administrators" setting for the "Use CAPTCHA for these users" setting. If you set this to Guests or All the global CAPTCHA works fine _as long as_ you have published the plugin you've selected in your Global Configuration _and_ configured the CAPTCHA plugin correctly.
