### ISSUE TITLE
Possible Bug Report

### ISSUE THREAD

**Issue by miamicityman** [akeeba/engage#59] opened 2020-12-17 18:59 UTC
If the contact is already a registered user but attempts to leave a comment without registering (as guest) using the registered email - error pops.

Using latest version of Joomla and most recent version of Engage.

Thanks,

**Comment by nikosdion** [comment] 2020-12-17 19:03
This is not a bug, it's a sensible feature. It doesn't let random people put words into your mouth.

If we would allow a guest user to leave a comment using a registered user's email address it would mean that the comment would be filed _as that registered user_. So you could come to my site and leave a message pretending to be me. This would effectively put your words into my mouth for everyone reading the conversation.

By preventing this with an error message which says that you need to login first we avoid that problem.

I am closing this as invalid.

**Closed by nikosdion** 2020-12-17 19:03 UTC
Labels: invalid

**Comment by miamicityman** [comment] 2020-12-30 16:35
Understood and agree. Thank you.
