### ISSUE TITLE
ACL problem

### ISSUE THREAD

**Issue by Pablo234** [akeeba/engage#52] opened 2020-07-24 19:29 UTC
If I enable edit own comments in guest I see you can edit whichever comment no matter if you are the owner or not

I try on different IP, in phone with 4g and my pc.

**Comment by nikosdion** [comment] 2020-07-25 07:19
Sorry, this is not a bug. Akeeba Engage does _exactly_ what you told it to do, even though what you told it to do makes no sense.

Guest comments are not owned by a user. Namely, the attached user ID is 0 which means "no user". As a result any non-logged-in user can edit every Guest comment.

You are about to complain that Guest comments have an email address, therefore we should use the email address to limit who can edit them. Unfortunately, you'd be wrong. Email addresses are NOT passwords. They are public or can at least be fairly easily guessed or retrieved (especially if you are using Gravatar). So it's really not a security solution. It's security theater.

If you want people submitting comments to be able to edit them _you must require them to log in first_. Does this make submitting comments harder? Yes, it does. Unless, of course, you also use something line Akeeba SocialLogin which reduces user friction by allowing people to do an one-click user registration and / or login using their Facebook, Google, Microsoft, Twitter, LinkedIn, GitHub etc account. This is what I did on my own blog for the very same reason.

I am closing this issue because what you describe is not a bug, it's the expected behavior -- even though it definitely makes no sense configuring the permissions this way.

**Closed by nikosdion** 2020-07-25 07:19 UTC
Labels: invalid
