### ISSUE TITLE
Public user could not post. Only registered users after login. Joomla 3.9.20 Engage 2.0.2

### ISSUE THREAD

**Issue by octaviobh** [akeeba/engage#95] opened 2021-07-10 15:02 UTC
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Be specific. You may link to one or more screenshots or a video as long as it's not the only clue you leave. Use words to describe what happens.

### Expected result

What you believed should have happened following the steps you outlined above.

### Actual result

What actually happened.

### Troubleshooting already performed

Please tell us about any troubleshooting you already performed and its results.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: x.y.z
* **PHP version**: x.y.z
* **Am I using HTTPS**: Yes or No
* **Server Operating System**: Windows, Linux, macOS, Don't Know
* **My device's Operating System**: Windows, Linux, macOS, iOS, Android...
* **My device's Operating System version**: e.g. macOS Mojave
* **Browser**: Chrome, Firefox, Edge, Internet Explorer, Safari, Opera, ...
* **Browser version**: x.y.z

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: x.y.z
* **Server type**: Apache, NginX, IIS, Lighttpd, LiteSpeed, ...
* **Server version**: x.y.z
* **Hosting company / Local server**: Enter the name of your site's hosting company or the prepackaged local server (e.g. MAMP, XAMPP, WAMPServer, ...) that you're using
* **Server Operating System version**: e.g. Windows 10, Ubuntu 16.04, ... Type N/A if it's a live host and you have no idea.

**Comment by nikosdion** [comment] 2021-07-10 15:18
It is not a bug when you have not configured the extension correctly. Please see https://github.com/akeeba/engage/wiki/Main-Concepts#joomla-permissions

This issue is closed as invalid as a result.

Finally, let me point out that you couldn't be bothered to fill in the basic information requested in the issue template. What you communicate is that you are lazy and very likely can't be bothered to do any troubleshooting. As a result I am not interested in having a conversation with you. The issue is, therefore, locked.

**Closed as completed by nikosdion** 2021-07-10 15:18 UTC
Labels: invalid
