### ISSUE TITLE
Content Plugin not loading Language files en-GB

### ISSUE THREAD

**Issue by bcordis** [akeeba/engage#233] opened 2022-12-22 16:06 UTC
### Steps to reproduce the issue

Install engage, enable Akeeba Engage Content plugin, and Go to Content, and the Engage tab will not show any language-translated strings plus its content.

### Expected result

The content Engage tab should show language-translated strings and their content.

### Actual result

The content Engage tab will not show any language-translated strings.

### Troubleshooting already performed

Ran language debug and does not show the plg_content_engage.ini file to be loaded. I verified files are there. No errors loading any files and strings, not in com_engage.

#### Mandatory information

* **Joomla! version**: 4.2.6 Stable
* **PHP version**: 8.0.12
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: macOS
* **My device's Operating System version**: macOS 13.1
* **Browser**: Chrome
* **Browser version**: 108.0.5359.124

#### Good to have information

* **MySQL version**: 5.7.29-log
* **Server type**: Apache
* **Server version**: ?
* **Hosting Company / Local server**: DreamHost
* **Server Operating System version**: N/A
### Additional comments

Let me know any additional testing I may do for you.

**Comment by nikosdion** [comment] 2022-12-22 16:09
Duplicate of https://github.com/akeeba/engage/discussions/231, already solved with https://github.com/akeeba/engage/issues/232

**Closed as completed by nikosdion** 2022-12-22 16:09 UTC
Labels: bug, duplicate
