### ISSUE TITLE
[OTHER] A few minor issues and suggestions

### ISSUE THREAD

**Issue by Kostelano** [akeeba/engage#30] opened 2020-05-13 23:05 UTC
Good afternoon! Today I got acquainted with your component (looking for an alternative to the comment component) and there are minor comments / suggestions.

1. I would like to see the CLEAN button, as all filters "hang until" you clean the filter field with your hands.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/81842891-77081a80-9555-11ea-99af-5f7662c11bfa.png)

2. If you marked the comment as possible spam (for example), the icon in the Enabled field is missing.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/81843084-c51d1e00-9555-11ea-9171-9a69089715c8.png)

3. In the action log the `{type}` variable is not translated. Of course, a translation for this constant is in Joomla.

![Screenshot_3](https://user-images.githubusercontent.com/8440661/81874551-c31f8300-9586-11ea-96fa-30eacb7a87cb.png)

4. I tested the component on the local PC. I added a manager to the site. After the comment was published by the 3rd user, the manager received a notification with the DELETE, MARK AS SPAM, etc. buttons. All links in the notification led to page 403.

Joomla 3.9.18
PHP 7.3.2

5. If possible, you need to adjust the styles to make it a little more colorful out of the box.

**Comment by nikosdion** [comment] 2020-05-14 06:34
Please do not file one mega-issue for 5 completely different and unrelated subjects. It makes tracking impossible for me. So, let's see everything one at a time and tell you whether you should file separate issues.

1. I can add that but it will only clear the text filters (text, title, email, IP). It will not change the enabled filter. I opened gh-31.

2. I cannot reproduce this issue. Moreover, this icon is rendered by Joomla, namely your active Joomla backend template. Since this is not coming from my code and works fine on a stock installation of Joomla with Akeeba Engage I consider it an invalid issue. Server and backend template issues are not something I can plausibly affect with my code.

3. This is a really complicated problem to solve. I created the issue gh-32 to track it.

4. The comment manager email is sent to any user who has the `core.edit.state` (Edit State) privilege for Akeeba Engage. This guarantees that all links will work _except_ for the "Delete" and "Spam and Delete" links (these require the additional core.delete a.k.a. Delete privilege). HOWEVER! If you are ALREADY logged into your site as a DIFFERENT user with less privileges than that then yes, of course, none of the manager links will ever work since your currently logged in user does not have the necessary privileges. When testing email links make sure you are logged in as the same user you are receiving the emails for. That should be self-understood. If you can reproduce this issue while logged in to your site as the user you received the email for please open a new issue and explicitly state the **effective permissions** for Akeeba Engage for the user who received the email.

5. I will have to decline that. You are given the full SCSS sources and instructions to create media overrides if you wish to customise any aspect of the extension's display. As a side note, please do keep in mind that overusing colour disorients able-bodied visitors to your site and can make your site inaccessible to visitors with disabilities.

I am closing this issue since the two reproducible problems already have another issue to track each one of them and I explained why I am not considering the other three to be valid issues.

**Closed by nikosdion** 2020-05-14 06:34 UTC

**Comment by Kostelano** [comment] 2020-07-03 17:39
I still reproduce problem number 2: there is no before pseudo-element icon.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/86489517-40889800-bd6d-11ea-8303-1736ea0d1c72.png)

**Comment by nikosdion** [comment] 2020-07-03 17:55
If you believe there is a problem please **file a new issue** as I told you a month and a half ago for the reasons I explained a month and a half ago. When you file a new issue you MUST include instructions for reproducing your issue. If you don't and I cannot reproduce your issue I will close it as invalid. Thank you.
